'use strict'

let fakeInfo = require('../seed_generator.js')

exports.seed = function(knex, Promise) {
  return knex.raw('ALTER SEQUENCE volunteer_id_seq RESTART WITH 16')
    .then(function() {
      return knex('volunteer').del()
    })
    .then(function () {
      return Promise.all([
        knex('volunteer').insert({
          id: 1,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Denver',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 2,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Denver',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 3,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Fort Collins',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 4,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Boulder',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 5,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Pueblo',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 6,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Mesa',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 7,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Pueblo',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 8,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Boulder',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 9,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Castle Pines',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 10,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Aurora',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 11,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Fort Collins',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 12,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Grand Junction',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 13,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Denver',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 14,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Greenley',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          about: fakeInfo.description(),
        }),
        knex('volunteer').insert({
          id: 15,
          user_name: fakeInfo.userName(),
          password: fakeInfo.password(),
          first_name: fakeInfo.firstName(),
          last_name: fakeInfo.lastName(),
          city: 'Boulder',
          state: 'CO',
          email: fakeInfo.email(),
          phone_number: fakeInfo.phone(),
          about: fakeInfo.description(),
        })
      ]);
    });
};
